ROM python:3.12-slim-bullseye

RUN useradd -U -m appuser && \
    mkdir /home/appuser/app && \
    chown -R appuser /home/appuser/app

USER appuser
WORKDIR /home/appuser/app

# Cache requirements in docker layer
COPY --chown=appuser requirements.txt requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --user -r requirements.txt

# Add local bin to PATH
ENV PATH=/home/appuser/.local/bin:$PATH

COPY --chown=appuser . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]