version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: case_rocket:pokedex
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: pokedex:db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
