version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: case_rocket:pokedex
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: pokedex:db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pokedex
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
