FROM python:3.12-slim-bullseye

# Adicionar usuário não root
RUN useradd -U -m appuser && \
    mkdir /home/appuser/app && \
    chown -R appuser /home/appuser/app

# Trocar para o usuário não root
USER appuser
WORKDIR /home/appuser/app

# Cache requirements em uma camada separada
COPY --chown=appuser requirements.txt requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --user -r requirements.txt

# Adicionar o bin local ao PATH
ENV PATH=/home/appuser/.local/bin:$PATH

# Copiar o código da aplicação
COPY --chown=appuser . .

# Comando para iniciar o servidor
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
